swagger: "3.0"
info:
  title: Recorded Future
  description: Automated generation of Recorded Future
  version: "1.0"
  contact:
    email: frikky@shuffler.io
    name: "@frikkylikeme"
    url: https://twitter.com/frikkylikeme
servers:
  - url: https://api.recordedfuture.com/v2
host: api.recordedfuture.com
basePath: /v2
schemes:
  - "https:"
paths:
  /alert/search:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Search Alert Rules
      description: Search Alert Rules
      parameters:
        - in: query
          name: Freetext Search
          description: Freetext search for an alert.
          required: true
          schema:
            type: string
  "/alert/{id}":
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Lookup Alert Notification
      description: Lookup Alert Notification
      parameters: []
  "/ip/{ip}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Lookup IP Address
      description: Lookup IP Address
      parameters:
        - in: query
          name: comment
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /malware/search:
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Lookup Malware
      description: Lookup Malware
      parameters:
        - in: query
          name: Malware
          description: Malware name or ID to lookup
          required: false
          schema:
            type: string
        - in: query
          name: Sightings
          description: Whether to include sightings fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Entity
          description: Whether to include entity fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Metrics
          description: Whether to include metrics fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Intel Card
          description: Whether to include intel card fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Analyst Notes
          description: Whether to include analyst notes fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Timestamps
          description: Whether to include timestamps fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Counts
          description: Whether to include counts fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Related Entities
          description: Whether to include related entities fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Categories
          description: Whether to include categories fields in output
          required: false
          schema:
            type: string
  /url/risklist:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Get URL Risk List
      description: Get URL Risk List
      parameters:
        - in: query
          name: format
          description: Limit content to entities matching a category/rule.
          required: false
          schema:
            type: string
        - in: query
          name: list
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /url/riskrules:
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future List URL Risk Rules
      description: URL Risk Rules
      parameters: []
  "/url/{url}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Lookup URL
      description: Recorded Future Lookup URL
      parameters: []
  /vulnerability/risklist:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Get Vulnerability Risk List
      description: Get Vulnerability Risk List
      parameters:
        - in: query
          name: format
          description: Limit content to entities matching a category/rule.
          required: false
          schema:
            type: string
        - in: query
          name: list
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /vulnerability/riskrules:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future List Vulnerability Risk Rules
      description: List Vulnerability Risk Rules
      parameters: []
  /vulnerability/search:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Lookup Vulnerability
      description: Lookup Vulnerability
      parameters:
        - in: query
          name: Related Links
          description: Whether to include related links in the output
          required: false
          schema:
            type: string
        - in: query
          name: NVD Description
          description: Whether to include NVD description fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Risk
          description: Whether to include risk fields in output
          required: false
          schema:
            type: string
        - in: query
          name: CPE 2.2 URI
          description: Whether to include CPE 2.2 URI fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Common Names
          description: Whether to include common names fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Vulnerability
          description: Vulnerability to lookup
          required: false
          schema:
            type: string
        - in: query
          name: CPE
          description: Whether to include CPE fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Threat Lists
          description: Whether to include threat lists fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Entity
          description: Whether to include entity fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Metrics
          description: Whether to include metrics fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Intel Card
          description: Whether to include intel card fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Analyst Notes
          description: Whether to include analyst notes fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Raw Risk
          description: Whether to include raw risk fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Timestamps
          description: Whether to include timestamps fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Counts
          description: Whether to include counts fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Related Entities
          description: Whether to include related entities fields in output
          required: false
          schema:
            type: string
        - in: query
          name: Sightings
          description: Whether to include sightings fields in output
          required: false
          schema:
            type: string
  /domain/risklist:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Get Domain Risk List
      description: Get Domain Risk List
      parameters:
        - in: query
          name: format
          description: Limit content to entities matching a category/rule.
          required: false
          schema:
            type: string
        - in: query
          name: list
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /domain/riskrules:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future List Domain Risk Rules
      description: List Domain Risk Rules
      parameters: []
  "/domain/{domain}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Lookup Domain
      description: Lookup Domain
      parameters:
        - in: query
          name: fields
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
        - in: query
          name: comment
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /hash/risklist:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Get Hash Risk List
      description: Get Hash Risk List
      parameters:
        - in: query
          name: format
          description: Limit content to entities matching a category/rule.
          required: false
          schema:
            type: string
        - in: query
          name: list
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /hash/riskrules:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future List Hash Risk Rules
      description: List Hash Risk Rules
      parameters: []
  "/hash/{hash}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Lookup Hash
      description: Lookup Hash
      parameters:
        - in: query
          name: fields
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
        - in: query
          name: comment
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /ip/risklist:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future Get IP Risk List
      description: Get IP Risk List
      parameters:
        - in: query
          name: format
          description: Limit content to entities matching a category/rule.
          required: false
          schema:
            type: string
        - in: query
          name: list
          description: Generated by shuffler.io OpenAPI
          required: false
          schema:
            type: string
  /ip/riskrules:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Recorded Future List IP Risk Rules
      description: List IP Risk Rules
      parameters: []
editing: false
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-RFToken
image: ""
securityDefinitions: {}
