swagger: "3.0"
info:
  title: Container Security v2
  description: >-
    Container Security API provides the endpoints for securing container images,
    for example, Docker. Using the API, you can you seamlessly and securely
    enable DevOps processes by providing visibility into the security of
    container images – including vulnerabilities, malware and policy violations
    – through integration with the build process.


    For background information about managing container security, see the [documentation site](https://docs.tenable.com/cloud/containersecurity/Content/ContainerSecurity/Welcome.htm).
  version: "1.0"
  contact:
    name: "@frikkylikeme"
    url: https://twitter.com/frikkylikeme
    email: frikky@shuffler.io
servers:
  - url: https://cloud.tenable.com/container-security/api/v2
host: cloud.tenable.com
basePath: /container-security/api/v2
schemes:
  - "https:"
paths:
  /images:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: List images
      description: Returns a paginated list of images. Use URL query parameters to filter
        the list. <p>Requires BASIC [16] user permissions. See <a
        href="/docs/permissions">Permissions</a>.</p>
      parameters:
        - in: query
          name: offset
          description: The number of skipped records in the returned result set. Must be in
            the int32 format.
          required: false
          schema:
            type: string
        - in: query
          name: limit
          description: The number of records to include in the result set. Must be in the
            int32 format. Default is 50. The maximum limit is 1,000.
          required: false
          schema:
            type: string
        - in: query
          name: name
          description: The image name to filter on. Tenable.io returns only the images with
            names that exactly match the parameter value. The value is
            case-sensitive.
          required: false
          schema:
            type: string
        - in: query
          name: repo
          description: The repository name to filter on. Tenable.io returns only the images
            from repositories that exactly match the parameter value. The value
            is case-sensitive.
          required: false
          schema:
            type: string
        - in: query
          name: tag
          description: The tag to filter on. Tenable.io returns only the images with tags
            that exactly match the parameter value. The value is case-sensitive.
          required: false
          schema:
            type: string
        - in: query
          name: hasMalware
          description: Specifies whether to return only the images with associated malware
            (images with the `numberOfMalware` attribute greater than 0).
          required: false
          schema:
            type: string
        - in: query
          name: score
          description: The score to filter on. Tenable.io limits results based on the
            parameter value and the comparison operator specified by the
            `scoreOperator` parameter. For more information about the risk score
            metric, see [Tenable.io Vulnerability Management User
            Guide](https://docs.tenable.com/cloud/containersecurity/Content/ContainerSecurity/RiskMetrics.htm).
          required: false
          schema:
            type: string
        - in: query
          name: scoreOperator
          description: >-
            The comparison operator for the value specified by the `score`
            parameter. Operators include:
             - EQ—equals
             - GT—greater than
             - EQ—less than
          required: false
          schema:
            type: string
        - in: query
          name: os
          description: The operating system to filter on. Tenable.io returns only the
            images with an operating system that exactly matches the parameter
            value.
          required: false
          schema:
            type: string
  "/images/{repository}/{image}/{tag}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Get image details
      description: Returns the details for an image specified by repository, name, and
        tag.<p>Requires BASIC [16] user permissions. See <a
        href="/docs/permissions">Permissions</a>.</p>
      parameters:
        - in: path
          name: repository
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: image
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: tag
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
    delete:
      responses:
        default:
          description: default
          schema: {}
      summary: Delete image
      description: Deletes an image specified by repository, name, and tag.<p>Requires SCAN
        OPERATOR [24] user permissions. See <a
        href="/docs/permissions">Permissions</a>.</p>
      parameters:
        - in: path
          name: repository
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: image
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: tag
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
  /repositories:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: List repositories
      description: Returns a list of image repositories in your Tenable.io Container
        Security instance. Use the query parameters to filter the list.
        <p>Requires BASIC [16] user permissions. See <a
        href="/docs/permissions">Permissions</a>.</p>
      parameters:
        - in: query
          name: imageName
          description: The repository name to filter on. Tenable.io Container Security
            returns only the repositories with names that exactly match the
            parameter value. The value is case-sensitive.
          required: false
          schema:
            type: string
        - in: query
          name: nameContains
          description: The partial repository name to filter on. Tenable.io Container
            Security returns the images with names that contain the parameter
            value. The value is case-sensitive.
          required: false
          schema:
            type: string
        - in: query
          name: offset
          description: The number of skipped records in the returned result set. Must be in
            the int32 format.
          required: false
          schema:
            type: string
        - in: query
          name: limit
          description: The number of records to include in the result set. Must be in the
            int32 format. Default is 50. The maximum limit is 1,000.
          required: false
          schema:
            type: string
  "/repositories/{name}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Get repository details
      description: Returns details for a Tenable.io Container Security
        repository.<p>Requires BASIC [16] user permissions. See <a
        href="/docs/permissions">Permissions</a>.</p>
      parameters:
        - in: path
          name: name
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
    delete:
      responses:
        default:
          description: default
          schema: {}
      summary: Delete repository
      description: Deletes a Tenable.io Container Security repository.<p>Requires SCAN
        OPERATOR [24] user permissions. See <a
        href="/docs/permissions">Permissions</a>.</p>
      parameters:
        - in: path
          name: name
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
  "/reports/{repository}/{image}/{tag}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Get image report
      description: Returns a vulnerability report for the specified image.<p>Requires BASIC
        [16] user permissions. See <a
        href="/docs/permissions">Permissions</a>.</p>
      parameters:
        - in: path
          name: repository
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: image
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: tag
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
editing: false
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-ApiKeys
image: ""
securityDefinitions: {}
