swagger: "3.0"
info:
  title: Tenable Downloads API
  description: >-
    The Downloads API allows you to access and download available Tenable
    products installation files and updates. You can use the API endpoints to
    list product pages, list downloads available for a specific product, and to
    download a file. The endpoints can also be used to determine and download
    latest version of a file to facilitate the automation of an installation.


    **Note:** Tenable Downloads API uses a different server URL than Tenable.io API: `https://www.tenable.com/downloads/api/v2/pages`.


    ### Authentication


    The Downloads API uses Bearer token authentication and requires a valid token in the Authorization header:

    ```

    Authorization: Bearer AbCdEf123456

    ```


    To access or reset your authentication token, navigate to the [Authentication Token](https://www.tenable.com/downloads/api_docs) page.
  version: "1.0"
  contact:
    name: "@frikkylikeme"
    url: https://twitter.com/frikkylikeme
    email: frikky@shuffler.io
servers:
  - url: https://www.tenable.com/downloads/api/v2
host: www.tenable.com
basePath: /downloads/api/v2
schemes:
  - "https:"
paths:
  /pages:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: List product pages
      description: Returns a list of product pages.
      parameters: []
  "/pages/{slug}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: List downloadable files for a product
      description: Returns a JSON hash of all download files for a given product page.
      parameters:
        - in: path
          name: slug
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
  "/pages/{slug}/files/{file}":
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Download a file
      description: Downloads a requested file.
      parameters:
        - in: path
          name: slug
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: file
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
editing: false
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-ApiKeys
image: ""
securityDefinitions: {}
